name: build docs

on: 
  push:
    branches: 
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: debug path
        run: echo $GITHUB_WORKSPACE$TEST_PATH
        env: 
          TEST_PATH: '/Lazer_Eyes/Docs/Docs.csproj'
