name: build docs

on: 
  push:
    branches: 
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      TEST_PATH: _site
    steps:
      - uses: actions/checkout@v3
      - name: debug path
        run: echo $GITHUB_WORKSPACE$TEST_PATH

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: ./$TEST_PATH
